version: '3'

services:
        app:
                build:
                        context: .
                        dockerfile: ./app/Dockerfile
                depends_on:
                        - redis
                ports:
                        - '3000:3000'
                container_name: node_app
                links:
                        - redis
        redis:
                build:
                        context: .
                        dockerfile: ./redis/Dockerfile
                restart: always
                volumes:
                        - ./data/redis:/data
                container_name: redis
